name: AI DevSecOps Security Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit detect-secrets semgrep

      - name: Run Bandit
        run: |
          bandit -r app -f json -o bandit-ci.json || true

      - name: Run Semgrep
        run: |
          semgrep scan \
            --config auto \
            --json \
            --output semgrep-ci.json \
            app || true

      - name: Run detect-secrets
        run: |
          detect-secrets scan --baseline .secrets.baseline

      
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key |
            gpg --dearmor |
            sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" |
            sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy SCA scan
        run: |
          trivy fs \
            --scanners vuln \
            --format json \
            --output trivy-sca-ci.json \
            . || true

      - name: Upload Trivy SCA report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sca-report
          path: trivy-sca-ci.json



      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-ci.json

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-ci.json